-- MySQL Script generated by MySQL Workbench
-- seg 27 set 2021 19:51:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema filmes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `filmes` ;

-- -----------------------------------------------------
-- Schema filmes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filmes` ;
USE `filmes` ;

-- -----------------------------------------------------
-- Table `filmes`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`genero` (
  `genero_id` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genero_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmes`.`preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`preco` (
  `preco_id` INT NOT NULL AUTO_INCREMENT,
  `filme_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `valor_entrada` INT NOT NULL,
  PRIMARY KEY (`preco_id`),
  INDEX `genero_id_idx` (`genero_id` ASC) VISIBLE,
  CONSTRAINT `genero_id`
    FOREIGN KEY (`genero_id`)
    REFERENCES `filmes`.`genero` (`genero_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `filmes`.`genero`
-- -----------------------------------------------------
START TRANSACTION;
USE `filmes`;
INSERT INTO `filmes`.`genero` (`genero_id`, `genero`) VALUES (1, 'Ação');
INSERT INTO `filmes`.`genero` (`genero_id`, `genero`) VALUES (2, 'Biográfico');
INSERT INTO `filmes`.`genero` (`genero_id`, `genero`) VALUES (3, 'Comédia');
INSERT INTO `filmes`.`genero` (`genero_id`, `genero`) VALUES (4, 'Drama');
INSERT INTO `filmes`.`genero` (`genero_id`, `genero`) VALUES (5, 'Comédia Româtica');

COMMIT;


-- -----------------------------------------------------
-- Data for table `filmes`.`preco`
-- -----------------------------------------------------
START TRANSACTION;
USE `filmes`;
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (1, 1, 1, 29.90);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (2, 2, 2, 30.70);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (3, 3, 2, 26.25);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (4, 4, 3, 17.80);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (5, 5, 4, 21.50);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (6, 6, 4, 18.00);
INSERT INTO `filmes`.`preco` (`preco_id`, `filme_id`, `genero_id`, `valor_entrada`) VALUES (7, 7, 5, 15.75);

COMMIT;

