-- MySQL Script generated by MySQL Workbench
-- dom 26 set 2021 20:35:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema normalization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema normalization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `normalization` ;
USE `normalization` ;

-- -----------------------------------------------------
-- Table `normalization`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `normalization`.`Setor` (
  `setor_id` INT NOT NULL,
  `setor_name` VARCHAR(100) NULL,
  PRIMARY KEY (`setor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normalization`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `normalization`.`Funcionario` (
  `Funcinario_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `setor_id` INT NOT NULL,
  PRIMARY KEY (`Funcinario_id`),
  INDEX `Setor_id_idx` (`setor_id` ASC) VISIBLE,
  CONSTRAINT `Setor_id`
    FOREIGN KEY (`setor_id`)
    REFERENCES `normalization`.`Setor` (`setor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normalization`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `normalization`.`Contato` (
  `Contato_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `Funcinario_id` INT NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`Contato_id`),
  INDEX `Funcionario_id_idx` (`Funcinario_id` ASC) VISIBLE,
  CONSTRAINT `Funcionario_id`
    FOREIGN KEY (`Funcinario_id`)
    REFERENCES `normalization`.`Funcionario` (`Funcinario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `normalization`.`Setor`
-- -----------------------------------------------------
START TRANSACTION;
USE `normalization`;
INSERT INTO `normalization`.`Setor` (`setor_id`, `setor_name`) VALUES (1, 'Administração, Vendas');
INSERT INTO `normalization`.`Setor` (`setor_id`, `setor_name`) VALUES (2, 'Operacional');
INSERT INTO `normalization`.`Setor` (`setor_id`, `setor_name`) VALUES (3, 'Estratégico, Vendas');
INSERT INTO `normalization`.`Setor` (`setor_id`, `setor_name`) VALUES (4, 'Marketing');

COMMIT;


-- -----------------------------------------------------
-- Data for table `normalization`.`Funcionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `normalization`;
INSERT INTO `normalization`.`Funcionario` (`Funcinario_id`, `nome`, `sobrenome`, `setor_id`) VALUES (12, 'Joseph', 'Rodrigues', 1);
INSERT INTO `normalization`.`Funcionario` (`Funcinario_id`, `nome`, `sobrenome`, `setor_id`) VALUES (13, 'André', 'Freeman', 2);
INSERT INTO `normalization`.`Funcionario` (`Funcinario_id`, `nome`, `sobrenome`, `setor_id`) VALUES (14, 'Cíntia', 'Duval', 3);
INSERT INTO `normalization`.`Funcionario` (`Funcinario_id`, `nome`, `sobrenome`, `setor_id`) VALUES (15, 'Fernanda', 'Mendes', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `normalization`.`Contato`
-- -----------------------------------------------------
START TRANSACTION;
USE `normalization`;
INSERT INTO `normalization`.`Contato` (`Contato_id`, `email`, `telefone`, `Funcinario_id`, `data_cadastro`) VALUES (1, 'jo@gmail.com', '(35)998552-1445', 12, '2020-05-05 08:50:25');
INSERT INTO `normalization`.`Contato` (`Contato_id`, `email`, `telefone`, `Funcinario_id`, `data_cadastro`) VALUES (2, 'andre1990@gmail.com', '(47)99522-4996', 13, '2020-02-05 00:00:00');
INSERT INTO `normalization`.`Contato` (`Contato_id`, `email`, `telefone`, `Funcinario_id`, `data_cadastro`) VALUES (3, 'cindy@outlook.com', '(33)99855-4669', 14, '2020-05-05 10:55:35');
INSERT INTO `normalization`.`Contato` (`Contato_id`, `email`, `telefone`, `Funcinario_id`, `data_cadastro`) VALUES (4, 'fernandamendes@yahoo.com', '(33)99200-1556', 15, '2020-05-05 11:45:40');

COMMIT;

